# Generated by Django 6.0.7 on 2026-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='house',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
